name: benchmark
on: pull_request

jobs:
  gobench:
    name: benchmarking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Go benchmark
      uses: bobheadxi/gobenchdata@master
      with:
        BENCHMARKS_OUT: .github/benchmarks.json
        GIT_COMMIT_MESSAGE: 'chore: add new benchmark'
        PRUNE_COUNT: 30
        GO_TEST_FLAGS: -cpu 1,2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
